### ISSUE TITLE
Add "working with lists" content

### ISSUE THREAD

**Issue by gilliganondata** [MarkEdmondson1234/dartistics.com#24]
Figuring out a way to explain and illustrate lists -- seems like there are some visuals that might be helpful.

**Comment by MarkEdmondson1234** [comment]
Check out the listviewer package with its jsonedit function - makes a nice interactive viewer of any list, and htmlwidget friendly.

**Comment by MarkEdmondson1234** [comment]
http://www.dartistics.com/learn-to-love-lists.html
