### ISSUE TITLE
Marketing Attribution with R package "ChannelAttribution"

### ISSUE THREAD

**Issue by kruse-alex** [MarkEdmondson1234/dartistics.com#26]
Hi Guys,

thank you for this awesome website. I work a lot with web tracking data and R and I might have another interesting example for your page. Find a good articel about it here (not from me): 

http://analyzecore.com/2016/08/03/attribution-model-r-part-1/

Cheers,
Alex

**Comment by MarkEdmondson1234** [comment]
I forgot to close this at the time, but this is live here now
http://www.dartistics.com/resources.html

Thanks!
